### ISSUE TITLE
style buttons

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/hugo-tiu#1]
request to add CSS style for buttons:

General style:

<img width="395" alt="image" src="https://user-images.githubusercontent.com/16557730/104090244-ce41c480-5275-11eb-9011-d606368b4524.png">

(e.g., from https://www.tilburguniversity.edu/current/news/more-news/corona-virus/faq-prospective-students#application)

Colors:
- provide two colors (the blue, and also this one):

https://www.tilburguniversity.edu/education/bachelors-programs/open-day

<img width="317" alt="image" src="https://user-images.githubusercontent.com/16557730/104090269-01845380-5276-11eb-826c-cc0737472642.png">

Current button style is: 

<img width="252" alt="image" src="https://user-images.githubusercontent.com/16557730/104090281-0fd26f80-5276-11eb-823a-5ffd6e50ac44.png">

**Comment by andreantonacci** [comment]
5b8df16
