### ISSUE TITLE
style headers

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/hugo-tiu#5]
The styling of the headers is suboptimal.

<img width="320" alt="image" src="https://user-images.githubusercontent.com/16557730/104124670-5bf2e200-5352-11eb-9fe9-d08c1cb7e3e4.png">

In particular, the fourth-level header (`#### four hashes`) is *larger*, or *thicker* than the third-level header.

Please rework the styling, so that its hierarchical structure isn't lost during visualization. Maybe switching H3 with H4 is already enough.

Code that rendered the image above:
```

# # One hash

## ## Two hashes

### ### Three hashes

#### #### Four hashes

##### ##### Five hashes

```

**Comment by andreantonacci** [comment]
b0c217a
